input_dir: "C:/Users/32780/Desktop/数模论文信息/minerU提取文件语料库/暂存"
output_dir: "../usable_data/cleaned_excellent_paper_mds"
profile: national_competition
separator: "##############"
reports_dir: "./reports"
